import { ARCHETYPES } from '../lib/archetypes.js';

const ARCHETYPE_IDS = ARCHETYPES.map(a => a.id).join(' ');

function bashScript(): string {
  return `\
_wt_completions() {
  local cur prev words cword
  _init_completion 2>/dev/null || {
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    words=("\${COMP_WORDS[@]}")
    cword=$COMP_CWORD
  }

  local commands="open create split list close remove rm init tldr completions"
  local archetypes="${ARCHETYPE_IDS}"

  if [[ $cword -eq 1 ]]; then
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
    return
  fi

  local cmd="\${words[1]}"
  case $cmd in
    open)
      case $prev in
        -w|--workers) return ;;
        --deploy-pool) return ;;
      esac
      COMPREPLY=($(compgen -W "-w --workers --deploy-pool --watcher --no-wizard" -- "$cur"))
      ;;
    split)
      case $prev in
        -a|--archetype)
          COMPREPLY=($(compgen -W "$archetypes" -- "$cur"))
          return
          ;;
      esac
      COMPREPLY=($(compgen -W "-v --vertical -f --focus -a --archetype --no-wizard" -- "$cur"))
      ;;
    completions)
      COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
      ;;
  esac
}

complete -F _wt_completions wt
complete -F _wt_completions worktree
`;
}

function zshScript(): string {
  return `\
#compdef wt worktree

_wt() {
  local -a commands archetypes
  commands=(
    'open:Create or switch to a worktree for an issue'
    'create:Start a new worktree without a ticket'
    'split:Split current tmux pane with a new Claude instance'
    'list:List all worktrees and their status'
    'close:Close the tmux window for an issue'
    'remove:Remove a worktree and close its tmux window'
    'rm:Remove a worktree and close its tmux window'
    'init:Initialize worktree configuration for the current repository'
    'tldr:Show quick examples and common usage patterns'
    'completions:Output shell completion script'
  )
  archetypes=(${ARCHETYPE_IDS})

  _arguments -C \\
    '(-h --help)'{-h,--help}'[Show help]' \\
    '(-V --version)'{-V,--version}'[Show version]' \\
    '1: :->command' \\
    '*: :->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case \$words[2] in
        open)
          _arguments \\
            '(-w --workers)'{-w,--workers}'[Number of Claude workers to spawn]:number' \\
            '--deploy-pool[Deploy a pre-configured worker pool]:pool' \\
            '--watcher[Spawn an overseer worker]' \\
            '--no-wizard[Skip archetype selection wizard]' \\
            '1:issue number'
          ;;
        split)
          _arguments \\
            '(-v --vertical)'{-v,--vertical}'[Split vertically]' \\
            '(-f --focus)'{-f,--focus}'[Focus the new pane after creation]' \\
            '(-a --archetype)'{-a,--archetype}'[Assign archetype role]:archetype:('"$ARCHETYPE_IDS"')' \\
            '--no-wizard[Skip the archetype selection wizard]' \\
            '1:issue number'
          ;;
        close|remove|rm)
          _arguments '1:issue number'
          ;;
        completions)
          _arguments '1:shell:(bash zsh fish)'
          ;;
      esac
      ;;
  esac
}

_wt "$@"
`;
}

function fishScript(): string {
  const archetypeCompletions = ARCHETYPES.map(
    a => `complete -c wt -n '__fish_seen_subcommand_from split' -s a -l archetype -d 'Archetype role' -r -a '${a.id}\\t${a.shortDescription}'`
  ).join('\n');

  return `\
# wt / worktree shell completions for fish
# Generated by: wt completions fish

# Erase existing completions
complete -c wt -e
complete -c worktree -e

# Subcommands
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a open      -d 'Create or switch to a worktree for an issue'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a create    -d 'Start a new worktree without a ticket'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a split     -d 'Split current tmux pane with a new Claude instance'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a list      -d 'List all worktrees and their status'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a close     -d 'Close the tmux window for an issue'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a remove    -d 'Remove a worktree and close its tmux window'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a rm        -d 'Remove a worktree and close its tmux window'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a init      -d 'Initialize worktree configuration for the current repository'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a tldr      -d 'Show quick examples and common usage patterns'
complete -c wt -f -n 'not __fish_seen_subcommand_from open create split list close remove rm init tldr completions' \\
  -a completions -d 'Output shell completion script'

# open options
complete -c wt -n '__fish_seen_subcommand_from open' -s w -l workers    -d 'Number of Claude workers to spawn' -r
complete -c wt -n '__fish_seen_subcommand_from open' -l deploy-pool     -d 'Deploy a pre-configured worker pool' -r
complete -c wt -n '__fish_seen_subcommand_from open' -l watcher         -d 'Spawn an overseer worker'
complete -c wt -n '__fish_seen_subcommand_from open' -l no-wizard       -d 'Skip archetype selection wizard'

# split options
complete -c wt -n '__fish_seen_subcommand_from split' -s v -l vertical  -d 'Split vertically'
complete -c wt -n '__fish_seen_subcommand_from split' -s f -l focus     -d 'Focus the new pane after creation'
complete -c wt -n '__fish_seen_subcommand_from split' -l no-wizard      -d 'Skip the archetype selection wizard'
${archetypeCompletions}

# completions shell arg
complete -c wt -f -n '__fish_seen_subcommand_from completions' -a 'bash\\tBash completion script'
complete -c wt -f -n '__fish_seen_subcommand_from completions' -a 'zsh\\tZsh completion script'
complete -c wt -f -n '__fish_seen_subcommand_from completions' -a 'fish\\tFish completion script'

# Mirror all completions to the 'worktree' alias
complete -c worktree --wraps wt
`;
}

function detectShell(): string | null {
  const shell = process.env.SHELL ?? '';
  if (shell.endsWith('zsh')) return 'zsh';
  if (shell.endsWith('bash')) return 'bash';
  if (shell.endsWith('fish')) return 'fish';
  return null;
}

function installHint(shell: string): string {
  switch (shell) {
    case 'bash':
      return [
        '# Installation (choose one):',
        '#   source <(wt completions bash)                    # add to ~/.bashrc',
        '#   wt completions bash > /etc/bash_completion.d/wt  # system-wide',
      ].join('\n');
    case 'zsh':
      return [
        '# Installation (choose one):',
        '#   source <(wt completions zsh)          # add to ~/.zshrc',
        '#   wt completions zsh > ~/.zfunc/_wt     # then: fpath=(~/.zfunc $fpath)',
      ].join('\n');
    case 'fish':
      return [
        '# Installation:',
        '#   wt completions fish > ~/.config/fish/completions/wt.fish',
      ].join('\n');
    default:
      return '';
  }
}

export function completionsCommand(shell?: string): void {
  const target = shell ?? detectShell();

  if (!target) {
    console.error('Could not detect shell. Specify one explicitly: wt completions <bash|zsh|fish>');
    process.exit(1);
  }

  let script: string;
  switch (target) {
    case 'bash':  script = bashScript();  break;
    case 'zsh':   script = zshScript();   break;
    case 'fish':  script = fishScript();  break;
    default:
      console.error(`Unknown shell "${target}". Supported: bash, zsh, fish`);
      process.exit(1);
  }

  const hint = installHint(target);
  if (hint) process.stderr.write(hint + '\n\n');
  process.stdout.write(script);
}
